### PR TITLE
Implement not and neq

### PR DESCRIPTION
**Pull request by nils-braun**
Fixing #37 and #38.

@kyprifog Would you like to check, if this solves your use-case?

### CODE REVIEW

**Comment by nils-braun** [comment]
Also related to #11

**Comment by kyprifog** [comment]
I was able to test
```
SELECT * from table where NOT col = 'value'
```
and this seems to work properly.   I'm still trying to figure out how to test
```
SELECT * from table where col IS NOT NULL
```
where i'm getting an error related to isnan.   I have to decide if this even makes sense, this aspect of dask/pandas is a bit more confusing than spark.

**Comment by martindurant** [comment]
^ @tomaugspurger , want to comment on the state of pandas nullable floats? I would say keep using pandas style `isnan`, and don't worry about NaN

**Comment by TomAugspurger** [comment]
Open PR at https://github.com/pandas-dev/pandas/pull/34307.

**Comment by nils-braun** [comment]
@kyprifog Thanks for testing! Could you maybe share some test data and the error message for the `NULL` case? Because for me, it seems to work:

```python
import dask
import dask_sql
import numpy as np

context = dask_sql.Context()
df = dask.datasets.timeseries()

# Fill in some NaN here and there
df["x"] = df["x"].apply(lambda x: np.NaN if x > 0 else x, meta=("x", "float64"))

context.register_dask_table(df, "timeseries")
print(context.sql("SELECT * FROM timeseries WHERE x IS NOT NULL", debug=True,).compute())
```

@martindurant I tried to read through the linked discussion (thanks for that!), but I am now a bit unsure what the current best usage is. Are you proposing to move to `df.isna` instead of `np.isnan`? Sorry if I understood this incorrectly...

**Comment by kyprifog** [comment]
@nils-braun I think the problem I was facing is most closely exemplified if you change your query above:
```
SELECT * FROM timeseries WHERE name IS NOT NULL
```
IE looking for `None` or its equivalent in a column with dtype O (object), which results in
```
E           TypeError("ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''")
```
Object is the default datatype inferred by dask for any string columns with missing values so this seems like a pretty common occurence.   Digging deeper it looks like that since object is a less specific in these cases the type for missing values is float.nan (even though the other values have type str), so this may be the connection that @martindurant is driving at.   This isn't strictly a sql-dask problem, but looking at pandas documentation it seems like there is still talk of a concept of nullable type for object dtype:  
https://pandas.pydata.org/pandas-docs/stable/user_guide/missing_data.html#missing-data

IE it should behave roughly like:
```
df.dropna(subset=["name"])
```
which works as expected.

**Comment by nils-braun** [comment]
Thank you @kyprifog for the excellent description. Now I finally understand :-)
This means, if moving to `df.isna` (which I did in the PR), should already solve the problem. At least your example use case works now:

```python
df["name"] = df["name"].apply(
    lambda x: None if x.startswith("A") else x, meta=("x", "object")
)

sql = "SELECT name IS NOT NULL FROM timeseries"
```

I have also added tests for this.

**Comment by kyprifog** [comment]
Tested on my end and works, and fix makes sense :+1:

**Pull request merged**
