### PR TITLE
Read from Intake Catalogs

### PR DESCRIPTION
**Pull request by nils-braun**
First part of #99 (the Apache Atlas part is still open).

This PR adds the functionality to read in from an Intake catalog. There are three possibilities:

```python
catalog = intake.open_catalog("catalog.yaml")
c.create_table("my_data", catalog, intake_table_name="intake_table")
```
or
```
c.create_table("my_data", "catalog.yaml", format="intake", intake_table_name="intake_table")
```
or via SQL:
```sql
    CREATE TABLE my_data WITH (
        format = 'intake',
        location = 'catalog.yaml'
    )
```
Additional arguments are passed to `to_dask`, except "intake_table_name" (which is optional and defaults to the dask-sql table name) and "catalog_kwargs", which are the arguments passed to "open_catalog".

Additionally, I have refactored the input util system to be pluggable, so that future additions are much easier to add.

### CODE REVIEW

**Comment by nils-braun** [comment]
If any of you (@ibnbay99 or @martindurant) has any additional comment on the usage, feel free to add a comment also later. I will merge now :-)

**Comment by martindurant** [comment]
I like this **a lot**!
Anaconda may wish to blog about this - unless you would like to write something we can share, @nils-braun ?

**Comment by nils-braun** [comment]
I am glad you like it! 
I wanted to write something for the next release (which should come in the next few days) and summarize all new features. But if you (or Anaconda) would like to pick this part up before, I am more than happy! Of course, I can support you in writing if you like.

**Comment by martindurant** [comment]
(apparently I didn't write anything...)

**Pull request merged**
