### PR TITLE
add binder badge

### LINKED ISSUE #59: Add binder badge
Would be useful to have a cluster available for someone who wants to quickly try. I'll be happy to help here.

### PR DESCRIPTION
**Pull request by raybellwaves**
Closes #59 

Had a very quick stab at this.

Couple things I need to look into:

- [x] Making sure the notebook pop-ups on entry
- [x] Ensuring the dashboard works

### CODE REVIEW

**Comment by raybellwaves** [comment]
The way to getting the dashboard to connect is probably somewhere in https://github.com/raybellwaves/xskillscore-tutorial

**Comment by mrocklin** [comment]
We might also consider adding an example to examples.dask.org .  

There is pretty good infrastructure there to render notebooks as docs, provide badges, set up dashboards automatically, and so on.  That site also gets decent traffic, which might help.

**Comment by raybellwaves** [comment]
Note: I could update the notebook to use `create_table` following https://github.com/nils-braun/dask-sql/pull/63
I can also check that the example in the README is up to date as the notebook uses that example.

**Comment by nils-braun** [comment]
Hi @raybellwaves!
Thank you so much for working on this! That is a very good addon to the project. I really love that it is showing the dask dashboard right away.
I do not have a strong opinion here, but: do you think it makes sense to include the notebooks also into this repository or keep them separate? I think both has benefits and drawbacks, but in terms of maintainability, I guess keeping them in one spot with the code might be favorable. What do you think?

**Comment by raybellwaves** [comment]
> include the notebooks also into this repository

I think this is a good idea.

In addition, you are welcome to fork my repo and we can work in yours. May be easier for maintenance and you don't have to wait for me to merge any PR's

**Comment by nils-braun** [comment]
Ok! I have created another PR in #72, which adds the forked repo (and the notebooks).

I am fine with both working in your or the forked repo :-) But sure, it might make sense to keep things together!

**Comment by raybellwaves** [comment]
Closed in favor of #72

**Pull request closed without merging**
